
# config/schema.py
schema = {
    "Payments_to_HCPs": [
        {"name": "type_1_npi", "type": "UInt64", "comment": "This column stores the National Provider Identifier (NPI), which is a unique identification number for covered health care providers.. Samples: [{'type_1_npi': 1003000126}, {'type_1_npi': 1003000142}, {'type_1_npi': 1003000167}]"},
        {"name": "life_science_firm_name", "type": "String", "comment": "This column contains the names of life science firms, identifying the organizations involved in the transactions.. Samples: [{'life_science_firm_name': 'TEVA PHARMACEUTICALS USA, INC.'}, {'life_science_firm_name': 'ABBVIE, INC.'}, {'life_science_firm_name': 'AMGEN INC.'}]"},
        {"name": "product_name", "type": "String", "comment": "This column lists the names of products associated with the life science firms, representing the items or services for which payments are made.. Samples: [{'product_name': 'JARDIANCE'}, {'product_name': 'FISHER & PAYKEL HEALTHCARE'}, {'product_name': 'EYLEA HD'}]"},
        {"name": "nature_of_payment", "type": "Nullable(String)", "comment": "This column describes the type of payments made, such as food and beverage, travel and lodging, or education, which provides context about the nature of the transactions.. Samples: [{'nature_of_payment': 'Food and Beverage'}, {'nature_of_payment': 'Travel and Lodging'}, {'nature_of_payment': 'Education'}]"},
        {"name": "year", "type": "UInt16", "comment": "This column indicates the year during which the payment was made, allowing for temporal analysis of financial interactions.. Samples: [{'year': 2016}, {'year': 2017}, {'year': 2018}]"},
        {"name": "amount", "type": "Nullable(Float32)", "comment": "This column reflects the monetary amount of the payment made, providing quantitative data for financial analysis.. Samples: [{'amount': 11.800000190734863}, {'amount': 16.09000015258789}, {'amount': 17.299999237060547}]"}
    ],
    "Provider_details_file": [
        {"name": "type_1_npi", "type": "UInt64"},
        {"name": "type_2_npi_names", "type": "Array(String)"},
        {"name": "type_2_npis", "type": "Array(UInt64)"},
        {"name": "first_name", "type": "String"},
        {"name": "middle_name", "type": "String"},
        {"name": "last_name", "type": "String"},
        {"name": "gender", "type": "Enum8('M' = 1, 'F' = 2, 'O' = 3, 'U' = 4, '' = 5)"},
        {"name": "specialties", "type": "Array(String)"},
        {"name": "conditions_tags", "type": "Array(Tuple(String, String))"},
        {"name": "conditions", "type": "Array(String)"},
        {"name": "cities", "type": "Array(String)"},
        {"name": "states", "type": "Array(String)"},
        {"name": "counties", "type": "Array(String)"},
        {"name": "city_states", "type": "Array(String)"},
        {"name": "hospital_names", "type": "Array(String)"},
        {"name": "system_names", "type": "Array(String)"},
        {"name": "affiliations", "type": "String"},
        {"name": "best_type_2_npi", "type": "UInt64"},
        {"name": "best_hospital_name", "type": "String"},
        {"name": "best_system_name", "type": "String"},
        {"name": "phone", "type": "Nullable(String)"},
        {"name": "email", "type": "Nullable(String)"},
        {"name": "linkedin", "type": "Nullable(String)"},
        {"name": "twitter", "type": "Nullable(String)"}
    ],
    "Referral_Patterns_file": [
        {"name": "primary_type_2_npi", "type": "UInt64"},
        {"name": "referring_type_2_npi", "type": "UInt64"},
        {"name": "primary_type_2_npi_city", "type": "String"},
        {"name": "referring_type_2_npi_city", "type": "String"},
        {"name": "primary_type_2_npi_state", "type": "String"},
        {"name": "referring_type_2_npi_state", "type": "String"},
        {"name": "primary_type_2_npi_postal_code", "type": "String"},
        {"name": "referring_type_2_npi_postal_code", "type": "String"},
        {"name": "primary_type_2_npi_lat", "type": "Float64"},
        {"name": "referring_type_2_npi_lat", "type": "Float64"},
        {"name": "primary_type_2_npi_lng", "type": "Float64"},
        {"name": "referring_type_2_npi_lng", "type": "Float64"},
        {"name": "primary_type_2_npi_name", "type": "String"},
        {"name": "referring_type_2_npi_name", "type": "String"},
        {"name": "primary_hospital_name", "type": "String"},
        {"name": "referring_hospital_name", "type": "String"},
        {"name": "primary_type_1_npi", "type": "UInt64"},
        {"name": "referring_type_1_npi", "type": "UInt64"},
        {"name": "primary_type_1_npi_name", "type": "String"},
        {"name": "referring_type_1_npi_name", "type": "String"},
        {"name": "primary_specialty", "type": "String"},
        {"name": "referring_specialty", "type": "String"},
        {"name": "date", "type": "Date"},
        {"name": "diagnosis_code", "type": "String"},
        {"name": "diagnosis_code_description", "type": "String"},
        {"name": "procedure_code", "type": "String"},
        {"name": "procedure_code_description", "type": "String"},
        {"name": "total_claim_charge", "type": "Float64"},
        {"name": "total_claim_line_charge", "type": "Float64"},
        {"name": "patient_count", "type": "UInt64"}
    ],
    "Diagnosis_Procedures_file": [
        {"name": "primary_type_2_npi", "type": "UInt64"},
        {"name": "PATIENT_ID", "type": "Int64"},
        {"name": "referring_type_2_npi", "type": "UInt64"},
        {"name": "primary_type_2_npi_city", "type": "String"},
        {"name": "referring_type_2_npi_city", "type": "String"},
        {"name": "primary_type_2_npi_state", "type": "String"},
        {"name": "referring_type_2_npi_state", "type": "String"},
        {"name": "primary_type_2_npi_postal_code", "type": "String"},
        {"name": "referring_type_2_npi_postal_code", "type": "String"},
        {"name": "primary_type_2_npi_lat", "type": "Float64"},
        {"name": "referring_type_2_npi_lat", "type": "Float64"},
        {"name": "primary_type_2_npi_lng", "type": "Float64"},
        {"name": "referring_type_2_npi_lng", "type": "Float64"},
        {"name": "primary_type_2_npi_name", "type": "String"},
        {"name": "referring_type_2_npi_name", "type": "String"},
        {"name": "primary_hospital_name", "type": "String"},
        {"name": "referring_hospital_name", "type": "String"},
        {"name": "primary_type_1_npi", "type": "UInt64"},
        {"name": "referring_type_1_npi", "type": "UInt64"},
        {"name": "primary_type_1_npi_name", "type": "String"},
        {"name": "referring_type_1_npi_name", "type": "String"},
        {"name": "primary_specialty", "type": "String"},
        {"name": "referring_specialty", "type": "String"},
        {"name": "date", "type": "Date"},
        {"name": "diagnosis_code", "type": "String"},
        {"name": "diagnosis_code_description", "type": "String"},
        {"name": "procedure_code", "type": "String"},
        {"name": "procedure_code_description", "type": "String"},
        {"name": "total_claim_charge", "type": "Float64"},
        {"name": "total_claim_line_charge", "type": "Float64"},
        {"name": "patient_count", "type": "UInt64"}
    ],
    "Pharmacy_Claims_file": [
        {"name": "RX_ANCHOR_DD", "type": "Date32"},
        {"name": "RX_CLAIM_NBR", "type": "String"},
        {"name": "PATIENT_ID", "type": "String"},
        {"name": "SERVICE_DATE_DD", "type": "Date32"},
        {"name": "TRANSACTION_STATUS_NM", "type": "String"},
        {"name": "REJECT_REASON_1_CD", "type": "String"},
        {"name": "REJECT_REASON_1_DESC", "type": "String"},
        {"name": "NDC", "type": "String"},
        {"name": "NDC_DESC", "type": "String"},
        {"name": "NDC_GENERIC_NM", "type": "String"},
        {"name": "NDC_PREFERRED_BRAND_NM", "type": "String"},
        {"name": "NDC_DOSAGE_FORM_NM", "type": "String"},
        {"name": "NDC_DRUG_FORM_NM", "type": "String"},
        {"name": "NDC_DRUG_NM", "type": "String"},
        {"name": "NDC_DRUG_SUBCLASS_NM", "type": "String"},
        {"name": "NDC_DRUG_CLASS_NM", "type": "String"},
        {"name": "NDC_DRUG_GROUP_NM", "type": "String"},
        {"name": "NDC_ISBRANDED_IND", "type": "String"},
        {"name": "PRESCRIBED_NDC", "type": "String"},
        {"name": "DIAGNOSIS_CD", "type": "String"},
        {"name": "DAW_CD", "type": "Int64"},
        {"name": "UNIT_OF_MEASUREMENT_CD", "type": "String"},
        {"name": "PRESCRIBER_NBR_QUAL_CD", "type": "String"},
        {"name": "PRESCRIBER_NPI_NBR", "type": "String"},
        {"name": "PRESCRIBER_NPI_NM", "type": "String"},
        {"name": "PRESCRIBER_NPI_ENTITY_CD", "type": "Int64"},
        {"name": "PRESCRIBER_NPI_HCO_CLASS_OF_TRADE_DESC", "type": "String"},
        {"name": "PRESCRIBER_NPI_HCP_SEGMENT_DESC", "type": "String"},
        {"name": "PRESCRIBER_NPI_STATE_CD", "type": "String"},
        {"name": "PRESCRIBER_NPI_ZIP5_CD", "type": "String"},
        {"name": "PAYER_ID", "type": "Int64"},
        {"name": "PAYER_PAYER_NM", "type": "String"},
        {"name": "PAYER_COB_SEQ_VAL", "type": "Int64"},
        {"name": "PAYER_PLAN_SUBCHANNEL_CD", "type": "String"},
        {"name": "PAYER_PLAN_SUBCHANNEL_NM", "type": "String"},
        {"name": "PAYER_PLAN_CHANNEL_CD", "type": "String"},
        {"name": "PAYER_PLAN_CHANNEL_NM", "type": "String"},
        {"name": "PAYER_COMPANY_NM", "type": "String"},
        {"name": "PAYER_MCO_ISSUER_ID", "type": "String"},
        {"name": "PAYER_MCO_ISSUER_NM", "type": "String"},
        {"name": "PAYER_BIN_NBR", "type": "String"},
        {"name": "PAYER_PCN_NBR", "type": "String"},
        {"name": "PAYER_GROUP_STR", "type": "String"},
        {"name": "FILL_NUMBER_VAL", "type": "Int64"},
        {"name": "DISPENSED_QUANTITY_VAL", "type": "Decimal(38,9)"},
        {"name": "PRESCRIBED_QUANTITY_VAL", "type": "Decimal(38,9)"},
        {"name": "DAYS_SUPPLY_VAL", "type": "Decimal(38,9)"},
        {"name": "NUMBER_OF_REFILLS_AUTHORIZED_VAL", "type": "Int64"},
        {"name": "GROSS_DUE_AMT", "type": "Decimal(38,9)"},
        {"name": "TOTAL_PAID_AMT", "type": "Decimal(38,9)"},
        {"name": "PATIENT_TO_PAY_AMT", "type": "Decimal(38,9)"},
        {"name": "AWP_UNIT_PRICE_AMT", "type": "Float64"},
        {"name": "AWP_CALC_AMT", "type": "Float64"}
    ],
    "Condition_Directory_file": [
        {"name": "projectId", "type": "Int32", "comment": "A unique identifier for the project associated with the condition. This helps in linking the conditions to specific research or clinical projects.. Samples: ['{\'projectId\': 2}', '{\'projectId\': 3}', '{\'projectId\': 4}']"},
        {"name": "display", "type": "Nullable(String)", "comment": "A human-readable name or description of the medical condition, making it easier for users to understand the condition being referenced.. Samples: ['{\'display\': \'Aagenaes Syndrome\'}', '{\'display\': \'Aase Syndrome\'}', '{\'display\': \'Aarskog Syndrome\'}']"},
        {"name": "codingType", "type": "Nullable(String)", "comment": "Indicates the type of coding used for the condition, such as whether it pertains to a condition or a procedure. This allows for categorization of the information.. Samples: ['{\'codingType\': \'condition\'}', '{\'codingType\': \'procedure\'}']"},
        {"name": "tcSize", "type": "Nullable(Int32)", "comment": "Represents the size of the clinical trial or data set related to the condition. This may reflect the number of cases or records available for analysis.. Samples: ['{\'tcSize\': 8069}', '{\'tcSize\': 14776}', '{\'tcSize\': 4188}']"}
    ],
    "KOL_Providers": [
        {"name": "npi", "type": "Int32", "comment": "The National Provider Identifier (NPI) is a unique identification number for healthcare providers used for billing and identification purposes.. Samples: ['{\'npi\': 1003000522}', '{\'npi\': 1003000530}', '{\'npi\': 1003000704}']"},
        {"name": "docId", "type": "Nullable(String)", "comment": "A unique identifier for a document associated with the provider, which can be used for referencing specific documents or records.. Samples: ['{\'docId\': \'8933264\'}', '{\'docId\': \'8642563\'}', '{\'docId\': \'12943480\'}']"},
        {"name": "personId", "type": "Nullable(Int32)", "comment": "An optional identifier linking the provider to a specific person in the database, useful for managing provider-specific data.. Samples: ['{\'personId\': 12940465}', '{\'personId\': 7623843}', '{\'personId\': 10178928}']"},
        {"name": "name", "type": "Nullable(String)", "comment": "The full name of the healthcare provider, helping to identify them in a user-friendly way.. Samples: ['{\'name\': \'Ardalan Enkeshafi\'}', '{\'name\': \'Rashid Khalil\'}', '{\'name\': \'Anna C. Morgan\'}']"},
        {"name": "displayName", "type": "Nullable(String)", "comment": "A name intended for display, which may differ from the provider\'s legal name and can be formatted for user-friendly viewing.. Samples: ['{\'displayName\': \'Dr. Carolina P. Larmeu\'}', '{\'displayName\': \'Dr. Michelle E. Romeo\'}', '{\'displayName\': \'Dr. Daniel L. Cornish\'}']"},
        {"name": "initials", "type": "Nullable(String)", "comment": "The initials of the healthcare provider, often used in documents or professional settings for brevity.. Samples: ['{\'initials\': \'DE\'}', '{\'initials\': \'KT\'}', '{\'initials\': \'SC\'}']"},
        {"name": "familyName", "type": "Nullable(String)", "comment": "The last name of the provider, which is commonly used for identification and search purposes.. Samples: ['{\'familyName\': \'Dr. Enkeshafi\'}', '{\'familyName\': \'Dr. Khalil\'}', '{\'familyName\': \'Dr. Morgan\'}']"},
        {"name": "score", "type": "Nullable(Float32)", "comment": "A score representing the provider\'s performance or quality, potentially based on patient feedback or other metrics.. Samples: ['{\'score\': 27.735431671142578}', '{\'score\': 41.36767578125}', '{\'score\': 37.84454345703125}']"},
        {"name": "phone", "type": "Nullable(String)", "comment": "The contact phone number for the healthcare provider, essential for patient communications.. Samples: ['{\'phone\': \'706-769-0005\'}', '{\'phone\': \'800-230-4565\'}', '{\'phone\': \'404-778-5299\'}']"},
        {"name": "isUSPrescriber", "type": "Nullable(Bool)", "comment": "A boolean value indicating whether the provider is authorized to prescribe medications in the United States.. Samples: ['{\'isUSPrescriber\': True}']"},
        {"name": "sex", "type": "Nullable(String)", "comment": "The gender of the healthcare provider, which can be relevant for patient preferences and demographic statistics.. Samples: ['{\'sex\': \'F\'}', '{\'sex\': \'M\'}']"},
        {"name": "image", "type": "Nullable(String)", "comment": "A URL link to an image of the healthcare provider, often used in profiles to enhance visual identification.. Samples: ['{\'image\': \'https://cdn.medifind.com/imgrepo/205734\'}', '{\'image\': \'https://cdn.medifind.com/imgrepo/203894\'}', '{\'image\': \'https://cdn.medifind.com/imgrepo/212690\'}']"},
        {"name": "primaryOrgName", "type": "Nullable(String)", "comment": "The name of the primary organization or employer associated with the provider, giving context to their practice.. Samples: ['{\'primaryOrgName\': \'Mary Washington Medical Group Hospitalist Services, LLC\'}', '{\'primaryOrgName\': \'Sylvania Pain Medicine\'}', '{\'primaryOrgName\': \'Oakland Medical Center\'}']"},
        {"name": "primaryOrgWebsite", "type": "Nullable(String)", "comment": "The website URL of the primary organization, allowing users to access more information about the provider\'s place of employment.. Samples: ['{\'primaryOrgWebsite\': \'https://www.adventhealth.com/practices/adventhealth-medical-group\'}', '{\'primaryOrgWebsite\': \'https://www.slhn.org/\'}', '{\'primaryOrgWebsite\': \'www.kch.org\'}']"},
        {"name": "highlyRatedConditionsCount", "type": "Nullable(Int32)", "comment": "The count of medical conditions for which the provider has received high ratings, reflecting their areas of expertise.. Samples: ['{\'highlyRatedConditionsCount\': 3}', '{\'highlyRatedConditionsCount\': 4}', '{\'highlyRatedConditionsCount\': 11}']"},
        {"name": "orgLogo", "type": "Nullable(String)", "comment": "A URL link to the logo of the provider\'s organization, used for branding purposes in directories or listings.. Samples: ['{\'orgLogo\': \'https://cdn.medifind.com/orgs/MayoClinic\'}', '{\'orgLogo\': \'https://cdn.medifind.com/orgs/ClevelandClinic\'}', '{\'orgLogo\': \'https://cdn.medifind.com/orgs/WeillCornellMedicine\'}']"},
        {"name": "orgWebsite", "type": "Nullable(String)", "comment": "The website URL of the provider\'s affiliated organization, where additional information and resources may be available.. Samples: ['{\'orgWebsite\': \'https://www.stmaryshealthcaresystem.org/medical-group/\'}', '{\'orgWebsite\': \'www.paeyes.com/\'}', '{\'orgWebsite\': \'www.emoryhealthcare.org/\'}']"},
        {"name": "healthSystem_website", "type": "Nullable(String)", "comment": "The website of the healthcare system the provider is associated with, providing a broader context for their services.. Samples: ['{\'healthSystem_website\': \'www.marywashingtonhealthcare.com/\'}', '{\'healthSystem_website\': \'www.mercy.com\'}', '{\'healthSystem_website\': \'thrive.kaiserpermanente.org/care-near-you/northern-california/\'}']"},
        {"name": "healthSystem_name", "type": "Nullable(String)", "comment": "The name of the healthcare system, useful for understanding the organizational structure in which the provider operates.. Samples: ['{\'healthSystem_name\': \'Piedmont Healthcare System\'}', '{\'healthSystem_name\': \'Geisinger\'}', '{\'healthSystem_name\': \'Emory Healthcare\'}']"},
        {"name": "codingCount", "type": "Nullable(Int32)", "comment": "The count of instances where medical coding is applied for the provider, indicating their activity level in documentation.. Samples: ['{\'codingCount\': 35}', '{\'codingCount\': 16}', '{\'codingCount\': 25}']"},
        {"name": "biography", "type": "Nullable(String)", "comment": "A brief biography of the healthcare provider, summarizing their background, expertise, and practice focus.. Samples: ['{\'biography\': \'<p>Ardalan Enkeshafi is an Internal Medicine doctor in Bethesda, Maryland. Dr. Enkeshafi has been practicing medicine for over 29 years and is highly rated in 1 condition, according to our data. His top areas of expertise are Sepsis, Peptic Ulcer, Necrosis, and Acute Kidney Failure. Dr. Enkeshafi is currently accepting new patients.</p>\'}', '{\'biography\': \'<p>Rashid Khalil is an Anesthesiologist and a Pain Medicine doctor in Toledo, Ohio. Dr. Khalil has been practicing medicine for over 24 years and is highly rated in 5 conditions, according to our data. His top areas of expertise are Chronic Pain, Spinal Stenosis, Sciatica, and Cervical Spondylosis. Dr. Khalil is currently accepting new patients.</p>\'}', '{\'biography\': \'<p>Anna Morgan is a Pediatrics doctor in Oakland, California.</p>\'}']"},
        {"name": "gradInstitution_year", "type": "Nullable(Int32)", "comment": "The year the provider graduated from their medical education institution, indicating their duration of practice.. Samples: ['{\'gradInstitution_year\': 2005}', '{\'gradInstitution_year\': 1999}', '{\'gradInstitution_year\': 2001}']"},
        {"name": "gradInstitution_gradYearNumber", "type": "Nullable(Int32)", "comment": "The year number in which the provider completed their degree, providing context on their educational timeline.. Samples: ['{\'gradInstitution_gradYearNumber\': 1994}', '{\'gradInstitution_gradYearNumber\': 1999}', '{\'gradInstitution_gradYearNumber\': 1997}']"},
        {"name": "gradInstitution_name", "type": "Nullable(String)", "comment": "The name of the educational institution where the provider graduated, valuable for verifying qualifications.. Samples: ['{\'gradInstitution_name\': \'Other\'}', '{\'gradInstitution_name\': \'Ohio State University College Of Medicine\'}', '{\'gradInstitution_name\': \'State University Of New York At Buffalo School Of Medicine\'}']"},
        {"name": "trainingInstitution_year", "type": "Nullable(Int32)", "comment": "The year the provider completed their training, which may reflect their level of expertise in their specialty.. Samples: []"},
        {"name": "trainingInstitution_gradYearNumber", "type": "Nullable(Int32)", "comment": "The year number for the provider\'s completion of training, offering insights into their professional development.. Samples: []"},
        {"name": "trainingInstitution_name", "type": "Nullable(String)", "comment": "The name of the training institution where the provider received their postgraduate education, adding to their credentials.. Samples: []"}
    ],
    "KOL_Scores": [
        {"name": "id", "type": "Int32", "comment": "A unique identifier for each score entry, ensuring that each row can be distinctly referenced.. Samples: ['{\'id\': 4351668}', '{\'id\': 4351669}', '{\'id\': 4351670}']"},
        {"name": "score", "type": "Nullable(Float32)", "comment": "The score value associated with a particular entry. It is represented as a nullable float, allowing for entries that may not have a score assigned.. Samples: ['{\'score\': 24.3745059967041}', '{\'score\': 23.595327377319336}', '{\'score\': 22.514259338378906}']"},
        {"name": "mf_providers_npi", "type": "Nullable(Int32)", "comment": "The National Provider Identifier (NPI) associated with the healthcare provider linked to the score. This is also nullable, accommodating cases where provider information might not be available.. Samples: ['{\'mf_providers_npi\': 1902805740}', '{\'mf_providers_npi\': 1326251471}', '{\'mf_providers_npi\': 1871028977}']"},
        {"name": "mf_conditions_projectId", "type": "Nullable(Int32)", "comment": "An identifier for the specific project related to the conditions assessed. This column is nullable, reflecting instances where the project ID may be absent.. Samples: ['{\'mf_conditions_projectId\': 4931}', '{\'mf_conditions_projectId\': 6074}', '{\'mf_conditions_projectId\': 6187}']"}
    ]
}
